### ISSUE TITLE
Failed to load dynlib/dll 'shcore'. Most likely this dynlib/dll was not found when the application was frozen.

### ISSUE THREAD

**Issue by mohamedelbadry** [audunarn/ANYstructure#129]
hello i am facing this error when i try to open program 
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 77, in __init__
  File "ctypes\__init__.py", line 376, in __init__
FileNotFoundError: Could not find module 'shcore' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "__main__.py", line 23, in <module>
  File "__main__.py", line 11, in main
  File "ctypes\__init__.py", line 446, in __getattr__
  File "PyInstaller\loader\pyimod03_ctypes.py", line 79, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'shcore'. Most likely this dynlib/dll was not found when the application was frozen.

**Comment by audunarn** [comment]
Hi,

This is the windows installer (.exe)?
i.e. you installed ANYstructure from this:
https://github.com/audunarn/ANYstructure/releases/tag/5.0.2


Audun

tir. 2. jan. 2024 kl. 11:39 skrev mohamedelbadry ***@***.***>:

**Comment by mohamedelbadry** [comment]
i think it is the same 
i installed from this [https://sourceforge.net/projects/anystructure/files/5.0.2/](url)

**Comment by audunarn** [comment]
Hmmm. I do not get the same error message when installing and running
the program. Hard to say what the error is. I don't think I can help you,
sorry.

tir. 2. jan. 2024 kl. 11:54 skrev mohamedelbadry ***@***.***>:
