### ISSUE TITLE
Multiple optimization (MultiOpt) not working.

### ISSUE THREAD

**Issue by audunarn** [audunarn/ANYstructure#2]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\Users\any\Code\PyStructural\ANY_structural\optimize_multiple_window.py", line 396, in run_optimizaion
    fp['p_ext']['loaded'], fp['p_ext']['ballast'], fp['p_ext']['part'] = 0,0,0
KeyError: 'p_ext'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\Users\any\Code\PyStructural\ANY_structural\optimize_multiple_window.py", line 396, in run_optimizaion
    fp['p_ext']['loaded'], fp['p_ext']['ballast'], fp['p_ext']['part'] = 0,0,0
KeyError: 'p_ext'

**Comment by audunarn** [comment]
Fixed.
